version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    container_name: n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_HOST=n8n-test-host.laminarmethods.co.uk
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n-test-host.laminarmethods.co.uk/
      - VUE_APP_URL_BASE_API=https://n8n-test-host.laminarmethods.co.uk/
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"  # Cloudflare Tunnel forwards this port
    networks:
      - n8n_network

volumes:
  n8n_data:

networks:
  n8n_network:
    driver: bridge